services:
  postgres:
    image: postgres:16-alpine
    container_name: powerbi-api-portfolio-postgres
    environment:
      POSTGRES_DB: github_bi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d github_bi"]
      interval: 3s
      timeout: 3s
      retries: 20

volumes:
  postgres_data:
